runmode: release # 开发模式, debug, release, test
addr: 8080 # http绑定端口
url: :8081

#### MySQL配置 ####
mysql:
  url: 127.0.0.1
  port: 3306
  username: root
  password: youxuan
  dbname: chatroom

gorm:
  max_open_conn: 600
  max_idle_conn: 550

#### SQLite配置 ####
sqlite_path: config/conf/chatroom.db

#### Redis配置 ####
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  # redis rooms key
  room_key: room
  room_user_key: room_user

  max_active_conn: 50
  max_idle_conn: 49


#### JWT ####
jwt:
  secret: chat-root-go
  # token 过期时间 单位：秒
  timeout: 3600