runmode: debug # 开发模式, debug, release, test
addr: 8080 # http绑定端口
url: 127.0.0.1:8080

#### MySQL配置 ####
mysql:
  url: 127.0.0.1
  prot: 3306
  username: root
  password: youxuan

#### SQLite配置 ####
sqlite_path: config/conf/chatroom.db


#### Redis配置 ####
redis:
  host: 127.0.0.1
  prot: 6379
  password: 123456


#### JWT ####
jwt:
  secret: chat-root-go
  # token 过期时间 单位：秒
  timeout: 3600