
###############
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "username": "youxuan",
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "password": "string",
  "phone": "string"
}

###############

###############
GET http://127.0.0.1:8080/userLogin?username=string&password=string

###############
GET http://127.0.0.1:8080/user/string

###############
POST http://127.0.0.1:8080/room
Content-Type: application/json

{
  "name": "小胖的直播间"
}

###############
GET http://127.0.0.1:8080/room/1416708659240

###############
POST http://127.0.0.1:8080/roomList
Content-Type: application/json

{
  "pageIndex": 0,
  "pageSize": 100
}

###############

POST http://127.0.0.1:8080/message/send
Content-Type: application/json

{
  "id": "1232134534532432",
  "text": "你好呀！"
}


###############
POST http://127.0.0.1:8080//message/retrieve
Content-Type: application/json

{
  "pageIndex": 0,
  "pageSize": 100
}